name: kubectl-argo-rollout-aws-eks
description: "This action provides kubectl and kubectl argo rollouts for Github Actions."
author: 'Maksim Karpychev, Maximilian Dewald'
runs:
  using: 'docker'
  image: 'Dockerfile'